name: 'AIFoundary Guardrail Scan'
description: 'Scan pull requests for unsafe AI prompts and configurations using AIFoundary.'
author: 'Pentaprime Solutions'

inputs:
  scan-path:
    description: 'Path to scan for AI risks'
    required: true
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'shield'
  color: 'blue'
